### ISSUE TITLE
Update Starter and Tutorial to be GA Compatible

### ISSUE THREAD

**Issue by epenning** [BroadleafCommerce/MicroservicesStarter#14]
Immediately after releasing RC6, we want to be sure we correctly ported over any necessary changes from our internal demo to the starter and release an RC6 compatible Starter and Tutorial

### Checklist

Changes made in Demo:
- [ ] [Cart service route properties](https://github.com/BroadleafCommerce/MicroservicesDemo/pull/42/files)
- [ ] Order service route properties
- [ ] Order service dependencies
- [ ] Remove `spring-integration-jdbc` and `spring-integration-mongo` Maven dependencies

**Comment by bpolster** [comment]
@elbertbautista - This ticket is in Soon but still tied to RC4. If it is part of RC4, move into Now or Next. If it is not, please remove the release.

**Comment by bpolster** [comment]
Changed this to RC6

**Comment by elbertbautista** [comment]
done
