### ISSUE TITLE
Apply OpenAPI client configuration from MicroservicesDemo

### ISSUE THREAD

**Issue by samarthd** [BroadleafCommerce/MicroservicesStarter#4]
Following the completion of BroadleafCommerce/MicroOpenAPI#187, the `MicroservicesDemo/services/authentication/src/main/resources/application-default.yml` file will have a complete set of permissions and scopes defined for the OpenAPI client. ~This client's configuration should be copied to `src/main/resources/application-default.yml` file in order to ensure authorization will work in this starter project.~ This client's configuration should be copied to the environment of the auth docker image in the `docker-compose.yml`

**Comment by samarthd** [comment]
While I haven't been able to get this to quite work yet, I believe at a minimum it will require us flattening out the properties and supplying them like so:
```yml
environment:
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_ID: 'OPENAPI'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SERVERID: '1'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_FRIENDLYNAME: 'OPENAPI CLIENT'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_CLIENTID: 'OPENAPI'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_CLIENTSECRET: '$$2A$$10$$1UDSYCCBX_THRTDUETCE6ECIVZEBC4BNMQVBYCPFOU/WQJ0Q40CK_'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_TOKENTIMEOUTSECONDS: '300'
  # BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_RESOURCEIDS:
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_GRANTTYPES[0]: 'CLIENT_CREDENTIALS'
  # BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_WHITELISTEDREDIRECTURIS:
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_ISADMIN: 'FALSE'
  # SCOPES
  # CATALOG SERVICE
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SCOPES[0]: 'PRODUCT'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SCOPES[1]: 'CATEGORY'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SCOPES[2]: 'PRODUCT_IGNORE_NARROWING'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SCOPES[3]: 'OPTION_TEMPLATE'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_SCOPES[4]: 'OPTION_TEMPLATE_GROUP'
  # PERMISSIONS
  # CATALOG SERVICE
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_PERMISSIONS[0]: 'ALL_PRODUCT'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_PERMISSIONS[1]: 'ALL_CATEGORY'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_PERMISSIONS[2]: 'ALL_OPTION_TEMPLATE'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_PERMISSIONS[3]: 'ALL_OPTION_TEMPLATE_GROUP'
  BROADLEAF_AUTH_DATA_LOAD_AUTHORIZEDCLIENTS[0]_PERMISSIONS[4]: 'ALL_PRODUCT_IGNORE_NARROWING'
```

This doesn't feel like a good pattern. 

@ncrum suggested an idea that maybe we should just add back the code-based OpenAPI client setup that we removed in https://github.com/BroadleafCommerce/AuthenticationServices/pull/151, and simply gate this usage on a simple boolean property. @elbertbautista What are your thoughts on this?

**Comment by samarthd** [comment]
@elbertbautista @ncrum I also just realized that if we modified the AuthenticationServices code, it wouldn't affect the starter since the starter is pointing at the older `rc2` image rather than anything newly built. If we plan to update the dependencies of the starter soon, then it'll be fine, but until that happens I believe the only way to make it work for now is to write out these flattened properties.

**Comment by ncrum** [comment]
Any changes to starter should be made in a `develop-1.0.0-rc3` branch. This will be where we will eventually target rc3, which has those changes.

Starter is almost never expected to be modified directly in develop since that is considered a stable branch targeting the latest release.

**Comment by samarthd** [comment]
>Any changes to starter should be made in a develop-1.0.0-rc3 branch. This will be where we will eventually target rc3, which has those changes.

I see. 

I looked at the `develop-1.0.0-rc3` branch, and those images still seem to be pointing to `rc2`:
- Auth image: https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop-1.0.0-rc3/docker-compose.yml#L81
- OpenAPI image: https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop-1.0.0-rc3/docker-compose.yml#L191

I presume the idea is right before we actually cut a release, these will all be modified to point to newer images? I suppose that means until then, we can't really expect to see this work unless I just temporarily change the image it's pointing to and run it locally to test it out.

**Comment by ncrum** [comment]
@samarthd feel free to update those images to point at the snapshot for the time being. Before merging into the `develop` branch, we will update to target the RC3 versions.

**Comment by samarthd** [comment]
@elbertbautista @ncrum 

I've created 3 PRs for this

- Define OpenAPI client in code and gate its usage on a new property: https://github.com/BroadleafCommerce/AuthenticationServices/pull/161
- Update the starter to use this property (and temporarily update its image references to point to the latest demo images in order to see these changes): https://github.com/BroadleafCommerce/MicroservicesStarter/pull/8
- Update the local and QA properties of the demo to use this new configuration: https://github.com/BroadleafCommerce/MicroservicesDemo/pull/36
