### ISSUE TITLE
Port over RC3 changes from demo to starter and tutorial

### ISSUE THREAD

**Issue by ncrum** [BroadleafCommerce/MicroservicesStarter#5]
Before releasing RC3, we want to be sure we correctly ported over any necessary changes from our internal demo to the starter. Generally, these additions should be made as we complete tasks, but it is sometimes easy to miss things.

To be certain, we should diff our internal demo and compare to a diff of the starter to detect anything missed, and then create a PR into `develop-1.0.0-rc3` with the fixed. Once RC3 is cut, we can merge `develop-1.0.0-rc3` into `develop` with the RC3 versions included and any other adjustments needed for the starter.

### Checklist

**MS Starter:**
- [x] Starter Pom: Zookeeper/Solr Creds: https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/pom.xml#L30-L90
- [x] Starter Pom: Use specific RC3 versions for dependencies rather than the snapshot versions introduced in https://github.com/BroadleafCommerce/MicroservicesStarter/pull/10
- [x] Docker Compose: Auth Cleanup:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.yml#L75-L77
- [x] Docker Compose: different auth image:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.yml#L81
- [x] Docker Compose: Validate Admin Gateway Config:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.yml#L9-L46
- [x] Docker Compose: Validate Commerce Gateway Config:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.yml#L97-L125
- [x] Docker Compose TGS: Validate OAuth Config:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.tgs.yml#L37-L39
- [x] Docker Compose TGS: ZK/Solr Creds: https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/docker-compose.tgs.yml#L42
- [x] Pom: ZK/Solr Creds:
https://github.com/BroadleafCommerce/MicroservicesStarter/blob/develop/pom.xml#L30-L94

**MS Tutorial:**
Make sure to do for:
- [x] https://github.com/BroadleafCommerce/MicroservicesTutorial/tree/develop/ms-tutorial-base
- [x] https://github.com/BroadleafCommerce/MicroservicesTutorial/tree/develop/ms-tutorial-extension-complete
- [x] https://github.com/BroadleafCommerce/MicroservicesTutorial/tree/develop/ms-tutorial-new-entity-complete

Issues:
- [x] Tutorial Base: Cleaned up Auth config: https://github.com/BroadleafCommerce/MicroservicesTutorial/blob/develop/ms-tutorial-base/docker-compose.yml#L52-L54
- [x] Tutorial Base: Different Demo Auth Image: https://github.com/BroadleafCommerce/MicroservicesTutorial/blob/develop/ms-tutorial-base/docker-compose.yml#L58

**Comment by elbertbautista** [comment]
done
